# Generated by Django 4.2.11 on 2024-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default-product-slug', unique=True),
            preserve_default=False,
        ),
    ]
