# Generated by Django 4.2.11 on 2024-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_ring_sets',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
